name: "snkgen"
description: "generate a snake game from a user's contributions grid. hard fork of Platane/snk."
author: "isitreallyalive"

runs:
  using: docker
  image: docker://isitreallyalive/snkgen@sha256:96390294299275740e5963058c9784c60c5393b3b8b16082dcf41b240db791f9

inputs:
  github_user_name:
    description: "GitHub username"
    required: true
  github_token:
    description: "GitHub token used to fetch the contribution calendar. default to the action token if empty."
    required: false
    default: ${{ github.token }}
  outputs:
    required: false
    description: |
      list of files to generate.
      one file per line. Each output can be customized with options as query string.

      supported options:
      - palette:        a preset of color, one of [github, github-dark, github-light]
      - color_snake:    color of the snake
      - color_dots:     comma separated list of dots color.
                        the first one is 0 contribution, then it goes from the low contribution to the highest.
                        exactly 5 colors are expected.
      - color_progress: color of the progress bar.

      example:
        outputs: |
          dark.svg?palette=github-dark&color_snake=blue
          light.svg?color_snake=#7845ab
          ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
